### PR TITLE
Rebuild for r-base-3.6.1

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #8 by replacing `.Platform$dynlib.ext` with `"so"` on OSX in the relevant line of code.

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge/r-rjags This is passing the builds, please review whether this is an acceptable workaround.

**Review by dpryan79 — APPROVED** [review]

**Comment by dpryan79** [comment]
This seems like a reasonable work around to me. Anyone else have thoughts before we click merge?

**Comment by dbast** [comment]
@dpryan79 The packages with workarounds are all mentioned so far in https://github.com/conda-forge/r-base-feedstock/issues/98 ... So we will find those again, in case those workarounds need to be reverted.

**Comment by dbast** [comment]
@xhochy Thanks!

**Pull request merged**
